### ISSUE TITLE
Error installing brainiak on MacOS M3 - AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?

### ISSUE THREAD

**Issue by nsossounov** [brainiak/brainiak#544]
Hi! 

Trying to install brainiak 0.11 from source on MacOS with an M3 chip, Python 3.12.5. Followed all instructions in the docs, running `echo $CC` returns `/usr/local/opt/llvm/bin/clang`. Still, the following error persists:

```
nikita@10-17-207-93 PyCharmProjects % python3 -m pip install brainiak

Collecting brainiak
  Using cached brainiak-0.11.tar.gz (6.8 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting cython (from brainiak)
  Using cached Cython-3.0.11-py2.py3-none-any.whl.metadata (3.2 kB)
Collecting mpi4py>=3 (from brainiak)
  Using cached mpi4py-4.0.0.tar.gz (464 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting nitime (from brainiak)
  Using cached nitime-0.11-cp312-cp312-macosx_11_0_arm64.whl.metadata (4.3 kB)
Requirement already satisfied: numpy!=1.17.* in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from brainiak) (2.1.0rc1)
Requirement already satisfied: scikit-learn>=0.18 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from scikit-learn[alldeps]>=0.18->brainiak) (1.5.1)
Requirement already satisfied: scipy!=1.0.0 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from brainiak) (1.14.0)
Collecting statsmodels (from brainiak)
  Using cached statsmodels-0.14.2-cp312-cp312-macosx_11_0_arm64.whl.metadata (9.2 kB)
Collecting pymanopt (from brainiak)
  Using cached pymanopt-2.2.0-py3-none-any.whl.metadata (7.0 kB)
Collecting theano>=1.0.4 (from brainiak)
  Using cached Theano-1.0.5.tar.gz (2.8 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [28 lines of output]
      /private/var/folders/5w/yksjh0fn5dnb6b_3pn99xdkc0000gn/T/pip-install-dgkmyvi4/theano_7c4166da14a24e32922018ed85b7b6f1/versioneer.py:421: SyntaxWarning: invalid escape sequence '\s'
        LONG_VERSION_PY['git'] = '''
      Traceback (most recent call last):
        File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/5w/yksjh0fn5dnb6b_3pn99xdkc0000gn/T/pip-build-env-pxydeanu/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 327, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/5w/yksjh0fn5dnb6b_3pn99xdkc0000gn/T/pip-build-env-pxydeanu/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 297, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/5w/yksjh0fn5dnb6b_3pn99xdkc0000gn/T/pip-build-env-pxydeanu/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 497, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/private/var/folders/5w/yksjh0fn5dnb6b_3pn99xdkc0000gn/T/pip-build-env-pxydeanu/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 313, in run_setup
          exec(code, locals())
        File "<string>", line 74, in <module>
        File "/private/var/folders/5w/yksjh0fn5dnb6b_3pn99xdkc0000gn/T/pip-install-dgkmyvi4/theano_7c4166da14a24e32922018ed85b7b6f1/versioneer.py", line 1412, in get_versions
          cfg = get_config_from_root(root)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/5w/yksjh0fn5dnb6b_3pn99xdkc0000gn/T/pip-install-dgkmyvi4/theano_7c4166da14a24e32922018ed85b7b6f1/versioneer.py", line 342, in get_config_from_root
          parser = configparser.SafeConfigParser()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

I assume this something to do with versioneer and Python completely removing SafeConfigParser in 3.12. I've tried do downgrade Python in my venv but it lead to more issues. Is there a solution to this apart from using Docker?

Thanks!

**Comment by mihaic** [comment]
Hello, @nsossounov. Thank you for sharing your experience trying to build BrainIAK on M3. We are working on automating the build and expanding support for newer Python version, but we have no ETA; you can see some work in the [pyproject_toml](https://github.com/davidt0x/brainiak/commits/pyproject_toml) branch. Generally speaking, we are stretched thin and would really appreciate code contributions.

**Comment by nsossounov** [comment]
@mihaic noted! no problem. will try to find some time to contribute
